#!/bin/bash
# Issue/PR へのコメント投稿スクリプト
# Bot名義またはユーザー名義でコメントを投稿
#
# 使用方法:
#   ./scripts/utils/comment_on_issue.sh <issue_number> [options]

set -e
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# IGNITE_CONFIG_DIR は .ignite/ から設定される（未設定時はPROJECT_ROOT/config）
IGNITE_CONFIG_DIR="${IGNITE_CONFIG_DIR:-$PROJECT_ROOT/config}"

# カラー定義
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# ログ出力（すべて標準エラー出力に出力して、コマンド置換で混入しないようにする）
log_info() { echo -e "${BLUE}[INFO]${NC} $1" >&2; }
log_success() { echo -e "${GREEN}[OK]${NC} $1" >&2; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# =============================================================================
# ヘルプ
# =============================================================================

show_help() {
    cat << 'EOF'
Issue/PR へのコメント投稿スクリプト

使用方法:
  ./scripts/utils/comment_on_issue.sh <issue_number> [オプション]

オプション:
  -r, --repo <repo>       リポジトリ（owner/repo形式）
  -b, --body <body>       コメント本文
  --body-file <file>      ファイルからコメント本文を読み込み
  -t, --template <type>   テンプレートを使用
                          (acknowledge, success, error, progress)
  -c, --context <text>    テンプレート内で使用するコンテキスト
  --bot                   Bot名義で投稿（GitHub App Token使用）
  -h, --help              このヘルプを表示

テンプレートタイプ:
  acknowledge   タスク受付時の応答
  success       処理完了時の応答
  error         エラー発生時の応答
  progress      進捗報告

使用例:
  # 直接メッセージ投稿
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --body "コメント内容"

  # Bot名義で投稿
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --bot --body "Bot応答"

  # テンプレート使用（受付応答）
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --bot --template acknowledge

  # テンプレート使用（成功報告）
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --bot \
    --template success --context "PR #456 を作成しました"

  # テンプレート使用（エラー報告）
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --bot \
    --template error --context "ビルドが失敗しました: npm test でエラー"

  # ファイルから本文を読み込んで投稿
  ./scripts/utils/comment_on_issue.sh 123 --repo owner/repo --bot \
    --body-file /tmp/comment_body.md

  # 現在のディレクトリからリポジトリを推測
  cd /path/to/repo
  ./scripts/utils/comment_on_issue.sh 123 --body "コメント"
EOF
}

# =============================================================================
# Bot Token / GitHub API 共通関数の読み込み
# =============================================================================

source "${SCRIPT_DIR}/github_helpers.sh"

# =============================================================================
# テンプレート生成
# =============================================================================

generate_from_template() {
    local template_type="$1"
    local context="${2:-}"

    case "$template_type" in
        acknowledge)
            cat <<'EOF'
このIssueを確認しました。処理を開始します。

---
*Generated by IGNITE AI Team*
EOF
            ;;
        success)
            cat <<EOF
✅ 処理が完了しました！

${context}

---
*Generated by IGNITE AI Team*
EOF
            ;;
        error)
            cat <<EOF
❌ 処理中にエラーが発生しました。

**エラー内容:**
${context}

---
*Generated by IGNITE AI Team*
EOF
            ;;
        progress)
            cat <<EOF
⏳ 処理中...

${context}

---
*Generated by IGNITE AI Team*
EOF
            ;;
        pr_created)
            cat <<EOF
✅ PRを作成しました！

${context}

レビューをお願いします。

---
*Generated by IGNITE AI Team*
EOF
            ;;
        review_complete)
            cat <<EOF
✅ レビューが完了しました！

${context}

---
*Generated by IGNITE AI Team*
EOF
            ;;
        *)
            log_error "Unknown template type: $template_type"
            exit 1
            ;;
    esac
}

# =============================================================================
# コメント投稿
# =============================================================================

post_comment() {
    local repo="$1"
    local issue_number="$2"
    local body="$3"
    local use_bot="$4"

    if [[ "$use_bot" == "true" ]]; then
        # リポジトリを渡してトークン取得（Organization対応）
        local bot_token
        bot_token=$(get_bot_token "$repo")
        if [[ -n "$bot_token" ]]; then
            log_info "Bot名義でコメントを投稿中... (REST API)"
            GH_TOKEN="$bot_token" gh api "/repos/${repo}/issues/${issue_number}/comments" \
                -f body="$body" --silent
            return $?
        fi
        # フォールバック: ペイン起動時の GH_TOKEN を確認
        if [[ -n "${GH_TOKEN:-}" && "${GH_TOKEN}" == ghs_* ]]; then
            log_warn "キャッシュBot Token取得失敗。環境変数GH_TOKENを使用します。"
            if gh api "/repos/${repo}/issues/${issue_number}/comments" \
                -f body="$body" --silent 2>/dev/null; then
                return 0
            fi
            log_warn "環境変数GH_TOKENでの投稿失敗（期限切れの可能性）。通常のトークンで投稿します。"
        else
            log_warn "Bot Token取得失敗。通常のトークンで投稿します。"
        fi
    fi

    log_info "コメントを投稿中..."
    env -u GH_TOKEN gh api "/repos/${repo}/issues/${issue_number}/comments" -f body="$body" --silent
}

# =============================================================================
# メイン
# =============================================================================

main() {
    local issue_number=""
    local repo=""
    local body=""
    local template=""
    local template_context=""
    local use_bot=false

    # 引数解析
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -r|--repo)
                repo="$2"
                shift 2
                ;;
            -b|--body)
                body="$2"
                shift 2
                ;;
            -t|--template)
                template="$2"
                shift 2
                ;;
            -c|--context)
                template_context="$2"
                shift 2
                ;;
            --body-file)
                if [[ -f "$2" ]]; then
                    body=$(cat "$2")
                else
                    log_error "ファイルが見つかりません: $2"
                    exit 1
                fi
                shift 2
                ;;
            --bot)
                use_bot=true
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            -*)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
            *)
                if [[ -z "$issue_number" ]]; then
                    issue_number="$1"
                fi
                shift
                ;;
        esac
    done

    # Issue番号チェック
    if [[ -z "$issue_number" ]]; then
        log_error "Issue番号を指定してください"
        echo ""
        show_help
        exit 1
    fi

    # リポジトリ推測
    if [[ -z "$repo" ]]; then
        repo=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || echo "")
        if [[ -z "$repo" ]]; then
            log_error "リポジトリを指定してください: --repo owner/repo"
            exit 1
        fi
        log_info "リポジトリを自動検出: $repo"
    fi

    # テンプレート使用
    if [[ -n "$template" ]]; then
        body=$(generate_from_template "$template" "$template_context")
    fi

    # 本文チェック
    if [[ -z "$body" ]]; then
        log_error "コメント本文を指定してください: --body, --body-file, または --template"
        exit 1
    fi

    # 投稿
    if post_comment "$repo" "$issue_number" "$body" "$use_bot"; then
        log_success "コメントを投稿しました: Issue #$issue_number"
    else
        log_error "コメント投稿に失敗しました"
        exit 1
    fi
}

main "$@"
