#!/bin/bash
# =============================================================================
# post_to_slack.sh — Slack スレッドへの返信投稿
#
# curl で chat.postMessage API を呼び出し、指定スレッドに返信を投稿する。
# comment_on_issue.sh と同様のインターフェースを提供。
#
# 使用方法:
#   ./scripts/utils/post_to_slack.sh --channel C01ABC --thread-ts 1234.5678 --body "応答"
# =============================================================================

set -e
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/core.sh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -n "${WORKSPACE_DIR:-}" ]] && setup_workspace_config "$WORKSPACE_DIR"

# =============================================================================
# ヘルプ
# =============================================================================

show_help() {
    cat << 'EOF'
Slack スレッドへの返信投稿スクリプト

使用方法:
  ./scripts/utils/post_to_slack.sh [オプション]

オプション:
  --channel <id>        チャンネル ID（必須）
  --thread-ts <ts>      返信先スレッドの ts（必須）
  --body <text>         メッセージ本文
  --body-file <file>    ファイルからメッセージ本文を読み込み
  --template <type>     テンプレートを使用
                        (acknowledge, success, error, progress)
  --context <text>      テンプレート内で使用するコンテキスト
  --dry-run             curl 実行せずコマンド表示（テスト用）
  -h, --help            このヘルプを表示

テンプレートタイプ:
  acknowledge   タスク受付時の応答
  success       処理完了時の応答
  error         エラー発生時の応答
  progress      進捗報告

使用例:
  # 直接メッセージ投稿
  ./scripts/utils/post_to_slack.sh --channel C01ABC --thread-ts 1234.5678 --body "応答内容"

  # テンプレート使用（受付応答）
  ./scripts/utils/post_to_slack.sh --channel C01ABC --thread-ts 1234.5678 --template acknowledge

  # テンプレート使用（成功報告）
  ./scripts/utils/post_to_slack.sh --channel C01ABC --thread-ts 1234.5678 \
    --template success --context "PR #456 を作成しました"

  # ファイルから本文を読み込み
  ./scripts/utils/post_to_slack.sh --channel C01ABC --thread-ts 1234.5678 \
    --body-file /tmp/response.txt
EOF
}

# =============================================================================
# トークン読み込み
# =============================================================================

_load_slack_token() {
    # 既に設定済みなら何もしない
    if [[ -n "${SLACK_TOKEN:-}" ]]; then
        return 0
    fi

    local env_file="${IGNITE_RUNTIME_DIR:-}/.env"
    if [[ -f "$env_file" ]]; then
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
            key=$(echo "$key" | tr -d '[:space:]')
            value=$(echo "$value" | sed 's/^["'"'"']//;s/["'"'"']$//')
            case "$key" in
                SLACK_TOKEN) export SLACK_TOKEN="$value" ;;
            esac
        done < "$env_file"
    fi

    if [[ -z "${SLACK_TOKEN:-}" ]]; then
        log_error "[post_to_slack] SLACK_TOKEN が設定されていません"
        return 1
    fi
}

# =============================================================================
# テンプレート生成（Slack mrkdwn 形式）
# =============================================================================

generate_slack_template() {
    local template_type="$1"
    local context="${2:-}"

    case "$template_type" in
        acknowledge)
            printf 'このリクエストを確認しました。処理を開始します。\n\n---\n_Generated by IGNITE AI Team_'
            ;;
        success)
            printf ':white_check_mark: 処理が完了しました！\n\n%s\n\n---\n_Generated by IGNITE AI Team_' "$context"
            ;;
        error)
            printf ':x: エラーが発生しました。\n\n*エラー内容:*\n%s\n\n---\n_Generated by IGNITE AI Team_' "$context"
            ;;
        progress)
            printf ':hourglass_flowing_sand: 処理中...\n\n%s\n\n---\n_Generated by IGNITE AI Team_' "$context"
            ;;
        *)
            log_error "[post_to_slack] 不明なテンプレート: $template_type"
            return 1
            ;;
    esac
}

# =============================================================================
# Slack 投稿
# =============================================================================

post_to_slack() {
    local channel="$1"
    local thread_ts="$2"
    local body="$3"
    local dry_run="${4:-false}"

    # JSON ペイロード構築
    local payload
    payload=$(jq -n \
        --arg channel "$channel" \
        --arg thread_ts "$thread_ts" \
        --arg text "$body" \
        '{channel: $channel, thread_ts: $thread_ts, text: $text}')

    if [[ "$dry_run" == "true" ]]; then
        echo "[DRY-RUN] curl -s -X POST https://slack.com/api/chat.postMessage"
        echo "[DRY-RUN] Authorization: Bearer \${SLACK_TOKEN}"
        echo "[DRY-RUN] Payload: ${payload}"
        return 0
    fi

    local response
    response=$(curl -s -X POST "https://slack.com/api/chat.postMessage" \
        -H "Authorization: Bearer ${SLACK_TOKEN}" \
        -H "Content-Type: application/json; charset=utf-8" \
        -d "$payload")

    local ok
    ok=$(echo "$response" | jq -r '.ok' 2>/dev/null)
    if [[ "$ok" != "true" ]]; then
        local error_msg
        error_msg=$(echo "$response" | jq -r '.error // "unknown error"' 2>/dev/null)
        log_error "[post_to_slack] Slack API エラー: ${error_msg}"
        return 1
    fi

    log_info "[post_to_slack] 投稿成功: channel=${channel} thread_ts=${thread_ts}"
}

# =============================================================================
# メイン
# =============================================================================

main() {
    local channel=""
    local thread_ts=""
    local body=""
    local template=""
    local template_context=""
    local dry_run=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --channel)
                channel="$2"
                shift 2
                ;;
            --thread-ts)
                thread_ts="$2"
                shift 2
                ;;
            --body)
                body="$2"
                shift 2
                ;;
            --body-file)
                if [[ -f "$2" ]]; then
                    body=$(cat "$2")
                else
                    log_error "[post_to_slack] ファイルが見つかりません: $2"
                    exit 1
                fi
                shift 2
                ;;
            --template)
                template="$2"
                shift 2
                ;;
            --context)
                template_context="$2"
                shift 2
                ;;
            --dry-run)
                dry_run=true
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "[post_to_slack] 不明なオプション: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # 必須引数チェック
    if [[ -z "$channel" ]]; then
        log_error "[post_to_slack] --channel は必須です"
        show_help
        exit 1
    fi
    if [[ -z "$thread_ts" ]]; then
        log_error "[post_to_slack] --thread-ts は必須です"
        show_help
        exit 1
    fi

    # テンプレート使用
    if [[ -n "$template" ]]; then
        body=$(generate_slack_template "$template" "$template_context")
    fi

    # 本文チェック
    if [[ -z "$body" ]]; then
        log_error "[post_to_slack] メッセージ本文を指定してください: --body, --body-file, または --template"
        show_help
        exit 1
    fi

    # トークン読み込み
    if [[ "$dry_run" != "true" ]]; then
        _load_slack_token
    fi

    # 投稿
    if post_to_slack "$channel" "$thread_ts" "$body" "$dry_run"; then
        log_success "[post_to_slack] Slack スレッドに投稿しました"
    else
        log_error "[post_to_slack] 投稿に失敗しました"
        exit 1
    fi
}

main "$@"
