# shellcheck shell=bash
# lib/cmd_help.sh - helpコマンド
[[ -n "${__LIB_CMD_HELP_LOADED:-}" ]] && return; __LIB_CMD_HELP_LOADED=1

# =============================================================================
# help コマンド
# =============================================================================

# shellcheck disable=SC2120  # Called with arguments from other files that source this library
cmd_help() {
    local command="${1:-}"

    case "$command" in
        start)
            echo "使用方法: ./scripts/ignite start [オプション]"
            echo ""
            echo "IGNITE システムを起動します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>    セッションIDを指定（未指定時は自動生成）"
            echo "  -w, --workspace <dir> ワークスペースディレクトリを指定"
            echo "  -n, --no-attach       起動後に自動アタッチしない"
            echo "  -f, --force           既存セッションを強制終了して再起動"
            echo "  -a, --agents <mode>   エージェント起動モード"
            echo "                          full:   全エージェント（デフォルト）"
            echo "                          leader: Leaderのみ"
            echo "                          sub:    Leader + Sub-Leaders（IGNITIANsなし）"
            echo "  --workers <N>         IGNITIANs並列数（1-32）"
            echo "  --no-workers          IGNITIANsを起動しない"
            echo "  --with-watcher        GitHub Watcherも一緒に起動"
            echo "  --no-watcher          GitHub Watcherを起動しない（設定で有効でも）"
            echo "  -h, --help            このヘルプを表示"
            echo ""
            echo "ペインレイアウト (fullモード):"
            echo "  pane 0:    Leader (伊羽ユイ)"
            echo "  pane 1-5:  Sub-Leaders (義賀リオ, 祢音ナナ, 衣結ノア, 通瀬アイナ, 恵那ツムギ)"
            echo "  pane 6+:   IGNITIANs (デフォルト3並列)"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite start                        # 全エージェント起動（自動ID）"
            echo "  ./scripts/ignite start -s proj-a              # セッションID指定で起動"
            echo "  ./scripts/ignite start -w /tmp/ws1            # ワークスペース指定で起動"
            echo "  ./scripts/ignite start -s proj-a -w /tmp/ws1  # 両方指定"
            echo "  ./scripts/ignite start -a leader              # Leaderのみ起動"
            echo "  ./scripts/ignite start -a sub                 # Leader + Sub-Leadersのみ"
            echo "  ./scripts/ignite start --workers 4            # IGNITIANs 4並列で起動"
            echo "  ./scripts/ignite start --with-watcher         # GitHub Watcherも起動"
            ;;
        stop)
            echo "使用方法: ./scripts/ignite stop [オプション]"
            echo ""
            echo "IGNITE システムを停止します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>  停止するセッションIDを指定"
            echo "  -y, --yes           確認をスキップ"
            echo "  -h, --help          このヘルプを表示"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite stop              # 実行中のセッションを停止"
            echo "  ./scripts/ignite stop -s proj-a    # 指定セッションを停止"
            echo "  ./scripts/ignite stop -y           # 確認なしで停止"
            ;;
        plan)
            echo "使用方法: ./scripts/ignite plan <目標> [オプション]"
            echo ""
            echo "タスクを投入します"
            echo ""
            echo "引数:"
            echo "  <目標>    実行したいタスクの目標"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>      対象セッションIDを指定"
            echo "  -w, --workspace <dir>   ワークスペースを指定"
            echo "  -c, --context <text>    コンテキストを追加"
            echo "  -h, --help              このヘルプを表示"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite plan \"READMEを作成する\""
            echo "  ./scripts/ignite plan \"認証機能を実装\" -c \"JWT認証、セッション管理\""
            echo "  ./scripts/ignite plan \"機能追加\" -s proj-a -w /tmp/ws-a"
            ;;
        status)
            echo "使用方法: ./scripts/ignite status [オプション]"
            echo ""
            echo "システムの状態を表示します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>      対象セッションIDを指定"
            echo "  -w, --workspace <dir>   ワークスペースを指定"
            echo "  -h, --help              このヘルプを表示"
            echo ""
            echo "表示内容:"
            echo "  - tmuxセッション状態"
            echo "  - ダッシュボード"
            echo "  - キュー状態"
            echo "  - レポート数"
            echo "  - 最新ログ"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite status"
            echo "  ./scripts/ignite status -s proj-a"
            ;;
        attach)
            echo "使用方法: ./scripts/ignite attach [オプション]"
            echo ""
            echo "tmuxセッションに接続します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>  接続するセッションIDを指定"
            echo "  -h, --help          このヘルプを表示"
            echo ""
            echo "tmux操作:"
            echo "  Ctrl+b d    セッションをデタッチ"
            echo "  Ctrl+b o    次のペインに移動"
            echo "  Ctrl+b [    スクロールモード"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite attach              # 実行中のセッションに接続"
            echo "  ./scripts/ignite attach -s proj-a    # 指定セッションに接続"
            ;;
        logs)
            echo "使用方法: ./scripts/ignite logs [オプション]"
            echo ""
            echo "ログを表示します"
            echo ""
            echo "オプション:"
            echo "  -w, --workspace <dir>  ワークスペースを指定"
            echo "  -f, --follow           リアルタイム監視 (tail -f)"
            echo "  -n, --lines <N>        表示行数 (デフォルト: 20)"
            echo "  -h, --help             このヘルプを表示"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite logs"
            echo "  ./scripts/ignite logs -f"
            echo "  ./scripts/ignite logs -w /tmp/ws-a -n 50"
            ;;
        clean)
            echo "使用方法: ./scripts/ignite clean [オプション]"
            echo ""
            echo "workspaceをクリアします"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>     対象セッションIDを指定"
            echo "  -w, --workspace <dir>  ワークスペースを指定"
            echo "  -y, --yes              確認をスキップ"
            echo "  -h, --help             このヘルプを表示"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite clean"
            echo "  ./scripts/ignite clean -w /tmp/ws-a -y"
            ;;
        activate)
            echo "使用方法: ./scripts/ignite activate [オプション]"
            echo ""
            echo "起動済みのエージェントをアクティベートします"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>  対象セッションIDを指定"
            echo "  -h, --help          このヘルプを表示"
            echo ""
            echo "説明:"
            echo "  起動時にシステムプロンプトが正しく実行されなかった場合に使用します。"
            echo "  各ペインに Enter を送信して、待機中のコマンドを実行させます。"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite activate"
            echo "  ./scripts/ignite activate -s proj-a"
            ;;
        notify)
            echo "使用方法: ./scripts/ignite notify <target> \"message\" [オプション]"
            echo ""
            echo "特定のエージェントにメッセージを送信します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>     対象セッションIDを指定"
            echo "  -w, --workspace <dir>  ワークスペースを指定"
            echo "  -h, --help             このヘルプを表示"
            echo ""
            echo "ターゲット:"
            echo "  leader, strategist, architect, evaluator, coordinator, innovator, ignitian_{n}"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite notify strategist \"戦略を立案してください\""
            echo "  ./scripts/ignite notify ignitian_1 \"タスク1を実行\" -s proj-a"
            ;;
        list)
            echo "使用方法: ./scripts/ignite list"
            echo ""
            echo "実行中のIGNITEセッション一覧を表示します"
            ;;
        work-on)
            echo "使用方法: ./scripts/ignite work-on <issue> [オプション]"
            echo ""
            echo "Issue番号を指定して実装を開始します"
            echo ""
            echo "引数:"
            echo "  <issue>    Issue番号またはURL"
            echo ""
            echo "オプション:"
            echo "  -r, --repo <repo>       リポジトリ（owner/repo形式）"
            echo "  -s, --session <id>      対象セッションIDを指定"
            echo "  -w, --workspace <dir>   ワークスペースを指定"
            echo "  -h, --help              このヘルプを表示"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite work-on 123 --repo owner/repo"
            echo "  ./scripts/ignite work-on https://github.com/owner/repo/issues/123"
            ;;
        watcher)
            echo "使用方法: ./scripts/ignite watcher <action>"
            echo ""
            echo "GitHub Watcherを管理します"
            echo ""
            echo "アクション:"
            echo "  start                       バックグラウンドで起動"
            echo "  stop                        停止"
            echo "  status                      状態確認"
            echo "  once                        単発実行"
            echo "  comment <issue> [options]   Issueにコメント投稿"
            echo "  ack <issue> [repo]          受付応答を投稿"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite watcher start"
            echo "  ./scripts/ignite watcher status"
            echo "  ./scripts/ignite watcher comment 123 --repo owner/repo --bot --body \"メッセージ\""
            echo "  ./scripts/ignite watcher ack 123 owner/repo"
            ;;
        cost)
            echo "使用方法: ./scripts/ignite cost [オプション]"
            echo ""
            echo "トークン消費量と概算費用を表示します"
            echo ""
            echo "オプション:"
            echo "  -s, --session <id>     対象セッションIDを指定"
            echo "  -w, --workspace <dir>  ワークスペースを指定"
            echo "  -a, --agent <role>     特定エージェントのみ表示"
            echo "  -d, --detailed         詳細表示（IGNITIANsの個別表示）"
            echo "  -j, --json             JSON形式で出力"
            echo "  -l, --list             コスト履歴一覧を表示"
            echo "  -h, --help             このヘルプを表示"
            echo ""
            echo "エージェント:"
            echo "  leader, strategist, architect, evaluator, coordinator, innovator, ignitians (全IGNITIAN)"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite cost                    # 現在のセッションのコスト"
            echo "  ./scripts/ignite cost -l                 # コスト履歴一覧"
            echo "  ./scripts/ignite cost -s proj-a          # 特定セッションのコスト"
            echo "  ./scripts/ignite cost -a leader          # Leaderのみ表示"
            echo "  ./scripts/ignite cost -d                 # 詳細表示"
            echo "  ./scripts/ignite cost -j                 # JSON出力"
            ;;
        "")
            echo -e "${BOLD}IGNITE${NC} - Intelligent Generative Networked Interaction-driven Task Engine"
            echo -e "IGNITEバージョン: v$VERSION"
            echo ""
            echo "使用方法: ./scripts/ignite <command> [options] [arguments]"
            echo ""
            echo "コマンド:"
            echo "  start     システムを起動"
            echo "  stop      システムを停止"
            echo "  list      実行中のセッション一覧"
            echo "  plan      タスクを投入"
            echo "  work-on   Issue番号を指定して実装開始"
            echo "  watcher   GitHub Watcherを管理"
            echo "  status    状態を確認"
            echo "  cost      トークン消費量・費用を表示"
            echo "  attach    tmuxセッションに接続"
            echo "  activate  エージェントをアクティベート"
            echo "  notify    エージェントに通知"
            echo "  logs      ログを表示"
            echo "  clean     workspaceをクリア"
            echo "  help      ヘルプを表示"
            echo ""
            echo "グローバルオプション:"
            echo "  -s, --session <id>    セッションIDを指定"
            echo "  -w, --workspace <dir> ワークスペースを指定"
            echo "  -h, --help            ヘルプを表示"
            echo "  -v, --version         バージョンを表示"
            echo ""
            echo "複数プロジェクト並行実行:"
            echo "  # プロジェクトAを起動"
            echo "  ./scripts/ignite start -s proj-a -w /tmp/workspace-a"
            echo ""
            echo "  # プロジェクトBを起動（別セッション）"
            echo "  ./scripts/ignite start -s proj-b -w /tmp/workspace-b"
            echo ""
            echo "  # セッション一覧確認"
            echo "  ./scripts/ignite list"
            echo ""
            echo "例:"
            echo "  ./scripts/ignite start"
            echo "  ./scripts/ignite plan \"READMEを作成する\""
            echo "  ./scripts/ignite status"
            echo "  ./scripts/ignite logs -f"
            echo ""
            echo "詳細なヘルプ:"
            echo "  ./scripts/ignite help <command>"
            ;;
        *)
            print_error "Unknown command: $command"
            cmd_help
            exit 1
            ;;
    esac
}
